hipchat: 
    room: ''
    auth_token: ''
    room_token: ''
    mention: 
        # - '@rei'

    allow: 'error|info'
    prefix: 'server-tpl'

slack: 
    webhookurl: ''
    channel: '#report'
    mention: 
        # - '@rei'

    allow: 'error|info'
    prefix: 'server-tpl'
    name: 'server-tpl'
    icon: ''